# Generated by Django 5.2.8 on 2025-12-01 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_vi', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_vi', models.TextField(blank=True)),
                ('license_type', models.CharField(choices=[('trial', 'Trial (30 days)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], max_length=20)),
                ('duration_days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('max_devices', models.PositiveIntegerField(default=1)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('license_type', models.CharField(choices=[('trial', 'Trial (30 days)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='trial', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
                ('max_devices', models.PositiveIntegerField(default=1)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hardware_id', models.CharField(db_index=True, max_length=128)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('os_info', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='users.license')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '[Legacy] Subscription',
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('heartbeat', 'Heartbeat'), ('activate', 'Device Activation'), ('deactivate', 'Device Deactivation'), ('license_check', 'License Check'), ('trade', 'Trade Executed'), ('error', 'Error')], max_length=50)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.deviceactivation')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='users.license')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_key', 'status'], name='users_licen_license_71b984_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['user', 'status'], name='users_licen_user_id_0819dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceactivation',
            unique_together={('license', 'hardware_id')},
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['license', 'timestamp'], name='users_usage_license_ceb88b_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['event_type', 'timestamp'], name='users_usage_event_t_ee8ee2_idx'),
        ),
    ]
