# Generated by Django 5.2.8 on 2025-12-01 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceactivation',
            options={'ordering': ['-last_seen'], 'verbose_name': 'Thiết bị', 'verbose_name_plural': 'Thiết bị đã kích hoạt'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['-created_at'], 'verbose_name': 'License', 'verbose_name_plural': 'Licenses'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['sort_order', 'price'], 'verbose_name': 'Gói đăng ký', 'verbose_name_plural': 'Gói đăng ký'},
        ),
        migrations.AlterModelOptions(
            name='usagelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Lịch sử hoạt động', 'verbose_name_plural': 'Lịch sử hoạt động'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
        migrations.AlterField(
            model_name='deviceactivation',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên thiết bị'),
        ),
        migrations.AlterField(
            model_name='deviceactivation',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lần đầu kết nối'),
        ),
        migrations.AlterField(
            model_name='deviceactivation',
            name='hardware_id',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Hardware ID'),
        ),
        migrations.AlterField(
            model_name='deviceactivation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP'),
        ),
        migrations.AlterField(
            model_name='deviceactivation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='deviceactivation',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heartbeat cuối'),
        ),
        migrations.AlterField(
            model_name='deviceactivation',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần cuối kết nối'),
        ),
        migrations.AlterField(
            model_name='deviceactivation',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='users.license', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='deviceactivation',
            name='os_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hệ điều hành'),
        ),
        migrations.AlterField(
            model_name='license',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày kích hoạt'),
        ),
        migrations.AlterField(
            model_name='license',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='license',
            name='expire_date',
            field=models.DateTimeField(verbose_name='Ngày hết hạn'),
        ),
        migrations.AlterField(
            model_name='license',
            name='features',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tính năng'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Mã license'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('trial', 'Dùng thử (30 ngày)'), ('monthly', 'Tháng'), ('quarterly', 'Quý (3 tháng)'), ('yearly', 'Năm'), ('lifetime', 'Vĩnh viễn')], default='trial', max_length=20, verbose_name='Loại license'),
        ),
        migrations.AlterField(
            model_name='license',
            name='max_devices',
            field=models.PositiveIntegerField(default=1, verbose_name='Số thiết bị tối đa'),
        ),
        migrations.AlterField(
            model_name='license',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('expired', 'Hết hạn'), ('suspended', 'Tạm dừng'), ('revoked', 'Thu hồi')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='license',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Đơn vị tiền'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description_vi',
            field=models.TextField(blank=True, verbose_name='Mô tả tiếng Việt'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(verbose_name='Số ngày'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tính năng'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Nổi bật'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='license_type',
            field=models.CharField(choices=[('trial', 'Dùng thử (30 ngày)'), ('monthly', 'Tháng'), ('quarterly', 'Quý (3 tháng)'), ('yearly', 'Năm'), ('lifetime', 'Vĩnh viễn')], max_length=20, verbose_name='Loại license'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_devices',
            field=models.PositiveIntegerField(default=1, verbose_name='Số thiết bị tối đa'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên gói'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name_vi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tên tiếng Việt'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.deviceactivation', verbose_name='Thiết bị'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='event_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='event_type',
            field=models.CharField(choices=[('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('heartbeat', 'Heartbeat'), ('activate', 'Kích hoạt thiết bị'), ('deactivate', 'Hủy kích hoạt'), ('license_check', 'Kiểm tra license'), ('trade', 'Giao dịch'), ('error', 'Lỗi')], max_length=50, verbose_name='Loại sự kiện'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='users.license', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='Avatar URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Giới thiệu'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quốc gia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Điện thoại'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token xác thực email',
                'verbose_name_plural': 'Token xác thực email',
            },
        ),
    ]
