# Generated by Django 5.2.8 on 2025-12-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_deviceactivation_options_alter_license_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='Mã kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='Số lần dùng tối đa')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Đã sử dụng')),
                ('trial_days', models.PositiveIntegerField(default=7, verbose_name='Số ngày Trial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Mã kích hoạt',
                'verbose_name_plural': 'Mã kích hoạt',
                'ordering': ['-created_at'],
            },
        ),
    ]
