# Generated by Django 5.2.8 on 2025-12-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên gói')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Số tháng')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá USD')),
                ('price_vnd', models.PositiveIntegerField(verbose_name='Giá VND')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Tính năng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Gói giá',
                'verbose_name_plural': 'Gói giá',
                'ordering': ['duration_months'],
            },
        ),
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('trial', 'Dùng thử (7 ngày)'), ('monthly', 'Tháng'), ('quarterly', 'Quý (3 tháng)'), ('yearly', 'Năm'), ('lifetime', 'Vĩnh viễn')], default='trial', max_length=20, verbose_name='Loại license'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='license_type',
            field=models.CharField(choices=[('trial', 'Dùng thử (7 ngày)'), ('monthly', 'Tháng'), ('quarterly', 'Quý (3 tháng)'), ('yearly', 'Năm'), ('lifetime', 'Vĩnh viễn')], max_length=20, verbose_name='Loại license'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_vnd', models.PositiveIntegerField(default=0, verbose_name='Số tiền VND')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số tiền USD')),
                ('order_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Mã đơn')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Mã giao dịch')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('completed', 'Thành công'), ('failed', 'Thất bại'), ('cancelled', 'Hủy'), ('refunded', 'Hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(choices=[('payos', 'PayOS (Bank)'), ('crypto', 'Crypto (USDT)'), ('manual', 'Thủ công')], default='payos', max_length=20, verbose_name='Phương thức')),
                ('payos_payment_link_id', models.CharField(blank=True, max_length=255, verbose_name='PayOS Link ID')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.license', verbose_name='License')),
                ('pricing_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.pricingplan', verbose_name='Gói giá')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
    ]
