# Generated by Django 5.2.8 on 2025-12-12 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_pricingplan_alter_license_license_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChangeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('license_updated', 'License Updated'), ('license_expired', 'License Expired'), ('license_renewed', 'License Renewed'), ('license_reduced', 'License Reduced'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated'), ('force_logout', 'Force Logout')], max_length=30, verbose_name='Loại thay đổi')),
                ('change_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu thay đổi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Đã gửi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo thay đổi',
                'verbose_name_plural': 'Thông báo thay đổi',
                'ordering': ['-created_at'],
            },
        ),
    ]
